### ISSUE TITLE
Option to disallow enabling video

### ISSUE THREAD

**Issue by GokulNC** [burkybang/Google-Meet-Auto-Disable-Mic-Cam#5]
I mostly use the shortcut Ctrl+D to mute & unmute.
Sometimes accidentally when muting, I press Ctrl+E, which enables my camera.

Would be great if you could add an option in the initial screen to disallow enabling video when in the call.
(This can either make the video button disabled, or hide it totally)

Thanks!

**Comment by burkybang** [comment]
Thanks for your feedback. I'm open to ideas, but this seems a little out of scope, and I'm not sure if I'd be able to impede Google's keyboard shortcut.

**Comment by GokulNC** [comment]
Thanks for the reply @burkybang . 

> _I'm not sure if I'd be able to impede Google's keyboard shortcut._

I was able to disable gmeet's Ctrl+E shortcut by doing the following:

```js
function blockVideoShortcut(e) {

    if (e.ctrlKey && e.key === 'e') {
        console.log("Blocking Ctrl+E shortcut which enables camera in gmeet.");
        e.preventDefault();
        e.stopPropagation();
    }
}

document.body.addEventListener('keydown', blockVideoShortcut, true);
```

One simple suggestion could be that we can add a checkbox called "Disable video shortcut (Ctrl+E)" which will register the above event handler when checked. When unchecked, it can remove the event handler by:

```js
document.body.removeEventListener('keydown', blockVideoShortcut, true);
```

**Comment by GokulNC** [comment]
Hii @burkybang 

Would you like a PR for this?

If you think this feature called "Disable video shortcut (Ctrl+E)" is out of scope for your extension, no problem :)
I can make a fork for my use case.

Thanks again!
