### ISSUE TITLE
Support for Opera browser

### ISSUE THREAD

**Issue by aswansyahputra** [burkybang/Google-Meet-Auto-Disable-Mic-Cam#8]
Hi,

I'm an avid user of this browser extension of yours, thank you for crafting this product. However, I've moved out from Chrome, and sadly, I discovered that this extension is not yet available in the Opera browser. Would it be within your bandwidth to add support for it?

Thank you!

**Comment by burkybang** [comment]
Does this help?

https://reddit.com/r/OperaGX/comments/17jilm3/how_to_add_chrome_webstore_extensions_onto_opera/

**Comment by aswansyahputra** [comment]
Awesome, it's working flawlessly. Thank you!

**Comment by burkybang** [comment]
Awesome!
